//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDARIO
    {
        public CALENDARIO()
        {
            this.BASES_LIQ = new HashSet<BASES_LIQ>();
        }
    
        public string CAL_PER { get; set; }
        public string CAL_VIG { get; set; }
        public System.DateTime CAL_FINI { get; set; }
        public System.DateTime CAL_FFIN { get; set; }
        public string CAL_CLA { get; set; }
        public string CAL_DES { get; set; }
        public string CAL_USBD { get; set; }
        public string CAL_USAP { get; set; }
        public Nullable<System.DateTime> CAL_FREG { get; set; }
        public Nullable<System.DateTime> CAL_FNOV { get; set; }
        public Nullable<System.DateTime> CAL_FVEN { get; set; }
    
        public virtual ICollection<BASES_LIQ> BASES_LIQ { get; set; }
    }
}
