//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BASES_LIQ> BASES_LIQ { get; set; }
        public DbSet<CALENDARIO> CALENDARIO { get; set; }
        public DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
        public DbSet<DIRECCIONES_EXTERNAS> DIRECCIONES_EXTERNAS { get; set; }
        public DbSet<FM_BASESLIQ01> FM_BASESLIQ01 { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<MUNICIPIOS> MUNICIPIOS { get; set; }
        public DbSet<ORA_ASPNET_MEMBERSHIP> ORA_ASPNET_MEMBERSHIP { get; set; }
        public DbSet<ORA_ASPNET_USERS> ORA_ASPNET_USERS { get; set; }
        public DbSet<SL_AGETDPTA> SL_AGETDPTA { get; set; }
        public DbSet<SL_DETLIQ> SL_DETLIQ { get; set; }
        public DbSet<SL_LIQESTAMPILLAS> SL_LIQESTAMPILLAS { get; set; }
        public DbSet<SL_PAGOS> SL_PAGOS { get; set; }
        public DbSet<SL_TERCEROS> SL_TERCEROS { get; set; }
        public DbSet<SL_TIPOPER> SL_TIPOPER { get; set; }
        public DbSet<SL_TIPORGM> SL_TIPORGM { get; set; }
        public DbSet<TDOC_IDE> TDOC_IDE { get; set; }
        public DbSet<TERCEROS> TERCEROS { get; set; }
        public DbSet<VIGENCIA> VIGENCIA { get; set; }
    }
}
