//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORA_ASPNET_USERS
    {
        public System.Guid APPLICATIONID { get; set; }
        public System.Guid USERID { get; set; }
        public string USERNAME { get; set; }
        public string LOWEREDUSERNAME { get; set; }
        public string MOBILEALIAS { get; set; }
        public decimal ISANONYMOUS { get; set; }
        public System.DateTime LASTACTIVITYDATE { get; set; }
    
        public virtual ORA_ASPNET_MEMBERSHIP ORA_ASPNET_MEMBERSHIP { get; set; }
    }
}
