//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_LIQESTAMPILLAS
    {
        public SL_LIQESTAMPILLAS()
        {
            this.SL_DETLIQ = new HashSet<SL_DETLIQ>();
            this.SL_PAGOS = new HashSet<SL_PAGOS>();
        }
    
        public decimal ID { get; set; }
        public string AGE_REC { get; set; }
        public Nullable<short> VIG_LIQ { get; set; }
        public Nullable<int> NRO_LIQ { get; set; }
        public string PER_LIQ { get; set; }
        public Nullable<System.DateTime> FEC_LIQ { get; set; }
        public string TER_NIT { get; set; }
        public string NUM_CTO { get; set; }
        public Nullable<System.DateTime> FEC_SUS { get; set; }
        public Nullable<System.DateTime> FEC_VEN { get; set; }
        public string ADI_CTO { get; set; }
        public string OBJ_CTO { get; set; }
        public Nullable<decimal> VAL_CTO { get; set; }
        public Nullable<decimal> VAL_BAS { get; set; }
        public string OBS_LIQ { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USUARIO { get; set; }
        public Nullable<decimal> SUB_TOT { get; set; }
        public Nullable<decimal> INTERES { get; set; }
        public Nullable<decimal> SANCION { get; set; }
        public Nullable<decimal> DECUENT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string ESTADO { get; set; }
        public string REPLICADO { get; set; }
        public string VIG_PAG { get; set; }
        public string PER_PAG { get; set; }
    
        public virtual ICollection<SL_DETLIQ> SL_DETLIQ { get; set; }
        public virtual ICollection<SL_PAGOS> SL_PAGOS { get; set; }
        public virtual SL_TERCEROS SL_TERCEROS { get; set; }
    }
}
