//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_TERCEROS
    {
        public SL_TERCEROS()
        {
            this.SL_LIQESTAMPILLAS = new HashSet<SL_LIQESTAMPILLAS>();
        }
    
        public int TER_CONS { get; set; }
        public string TER_TDOC { get; set; }
        public string TER_NIT { get; set; }
        public string TER_DVER { get; set; }
        public string TER_PER { get; set; }
        public string TER_RGM { get; set; }
        public string TER_NOM { get; set; }
        public string TER_TEL { get; set; }
        public string TER_EMAI { get; set; }
        public string TER_DIR { get; set; }
        public string TER_MPIO { get; set; }
        public Nullable<System.DateTime> FEC_REG { get; set; }
        public string USUARIO { get; set; }
    
        public virtual ICollection<SL_LIQESTAMPILLAS> SL_LIQESTAMPILLAS { get; set; }
        public virtual SL_TIPOPER SL_TIPOPER { get; set; }
        public virtual SL_TIPORGM SL_TIPORGM { get; set; }
        public virtual TDOC_IDE TDOC_IDE { get; set; }
    }
}
