//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SL_TIPORGM
    {
        public SL_TIPORGM()
        {
            this.SL_TERCEROS = new HashSet<SL_TERCEROS>();
        }
    
        public string COD_TIP { get; set; }
        public string NOM_TIP { get; set; }
    
        public virtual ICollection<SL_TERCEROS> SL_TERCEROS { get; set; }
    }
}
