--DROP TABLE SL_PAGOS;
--DROP TABLE SL_DETLIQ;
--DROP TABLE SL_LIQESTAMPILLAS;
--DROP TABLE SL_AGETDPTA;
--DROP TABLE SL_TERCEROS; 
--DROP TABLE SL_TIPOPER;
--DROP TABLE SL_TIPORGM;

CREATE TABLE SL_AGETDPTA(
    TER_NIT VARCHAR2(15)
);

ALTER TABLE SL_AGETDPTA
 ADD CONSTRAINT SL_AGETDPTA_PK
 PRIMARY KEY
 (TER_NIT);
 
 
COMMENT ON TABLE SL_AGETDPTA IS 'AGENTES DEPARTAMENTALES'
/

COMMENT ON COLUMN SL_AGETDPTA.TER_NIT IS 'IDE DEL AGENTE'
/

CREATE TABLE SL_TIPOPER(
    COD_TIP VARCHAR2(2),
    NOM_TIP VARCHAR2(2)
);


COMMENT ON TABLE SL_TIPOPER IS 'TIPO DE PERSONA'
/

COMMENT ON COLUMN SL_TIPOPER.COD_TIP IS 'CODIGO'
/

COMMENT ON COLUMN SL_TIPOPER.NOM_TIP IS 'NOMBRE '
/

ALTER TABLE SL_TIPOPER
 ADD CONSTRAINT SL_TIPOPER_PK
 PRIMARY KEY
 (COD_TIP);


CREATE TABLE SL_TIPORGM(
    COD_TIP VARCHAR2(2),
    NOM_TIP VARCHAR2(2)
);

COMMENT ON TABLE SL_TIPORGM IS 'TIPO DE REGIMEN '
/

COMMENT ON COLUMN SL_TIPORGM.COD_TIP IS 'CODIGO'
/

COMMENT ON COLUMN SL_TIPORGM.NOM_TIP IS 'NOMBRE '
/

ALTER TABLE SL_TIPORGM
 ADD CONSTRAINT SL_TIPORGM_PK
 PRIMARY KEY
 (COD_TIP); 
 

CREATE TABLE SL_TERCEROS(
   TER_CONS     NUMBER(10)                       NOT NULL,
   TER_TDOC     VARCHAR2(2 BYTE)                 NOT NULL,
   TER_NIT      VARCHAR2(15 BYTE)                NOT NULL,
   TER_DVER     VARCHAR2(1 BYTE),
   TER_PER      VARCHAR2(2 BYTE)                 NOT NULL,
   TER_RGM      VARCHAR2(2 BYTE)                 NOT NULL,
   TER_NOM      VARCHAR2(100 BYTE)               NOT NULL,
   TER_TEL      VARCHAR2(25 BYTE),
   TER_EMAI     VARCHAR2(100 BYTE),
   TER_DIR      VARCHAR2(75 BYTE),
   TER_MPIO     VARCHAR2(6 BYTE)                 NOT NULL,
   FEC_REG DATE,
   USUARIO VARCHAR(20)
);


COMMENT ON TABLE SL_TERCEROS IS 'SL TERCERO MOD LIQUIDACION INDIVIDUL';

COMMENT ON COLUMN SL_TERCEROS.TER_CONS IS 'CONSECUTIVO';

COMMENT ON COLUMN SL_TERCEROS.TER_TDOC IS 'TIPO DE DOCUMENTO';

COMMENT ON COLUMN SL_TERCEROS.TER_NIT IS 'NIT O IDENTIFICACION';

COMMENT ON COLUMN SL_TERCEROS.TER_DVER IS 'DIGITO VERIFICACION';

COMMENT ON COLUMN SL_TERCEROS.TER_PER IS 'TIPO DE PERSONA (NATIRUAL O JURIDICA)';

COMMENT ON COLUMN SL_TERCEROS.TER_RGM IS 'TIPO REGIMEN';

COMMENT ON COLUMN SL_TERCEROS.TER_NOM IS 'NOMBRE TERCERO';

COMMENT ON COLUMN SL_TERCEROS.TER_TEL IS 'TELEFONO';

COMMENT ON COLUMN SL_TERCEROS.TER_EMAI IS 'CORREO ELECTRONICO';

COMMENT ON COLUMN SL_TERCEROS.TER_DIR IS 'DIRECCION';

COMMENT ON COLUMN SL_TERCEROS.TER_MPIO IS 'MUNICIPIO';

COMMENT ON COLUMN SL_TERCEROS.FEC_REG IS 'FECHA DE REGISTRO';

COMMENT ON COLUMN SL_TERCEROS.USUARIO IS 'USUARIO';

ALTER TABLE SL_TERCEROS
 ADD CONSTRAINT SL_TERCEROS_PK
 PRIMARY KEY
 (TER_NIT);

ALTER TABLE SL_TERCEROS
 ADD CONSTRAINT SL_TERCEROS_FK_TDOC 
 FOREIGN KEY (TER_TDOC) 
 REFERENCES TDOC_IDE (TDOC_COD);
 
 ALTER TABLE SL_TERCEROS
 ADD CONSTRAINT SL_TERCEROS_FK_PER 
 FOREIGN KEY (TER_PER) 
 REFERENCES SL_TIPOPER (COD_TIP);

ALTER TABLE SL_TERCEROS
 ADD CONSTRAINT SL_TERCEROS_FK_RGM 
 FOREIGN KEY (TER_RGM) 
 REFERENCES SL_TIPORGM (COD_TIP);


CREATE TABLE SL_LIQESTAMPILLAS (
    ID NUMBER(20),
    AGE_REC VARCHAR2(15 BYTE),
    VIG_LIQ NUMBER(4),
    NRO_LIQ NUMBER(10),
    PER_LIQ VARCHAR2(2),
    FEC_LIQ DATE, 
    TER_NIT VARCHAR2(15 BYTE),
 
    
    NUM_CTO VARCHAR2(10),
    FEC_SUS DATE,
    FEC_VEN DATE,    
    ADI_CTO VARCHAR2(1),
    OBJ_CTO VARCHAR2(2000),
    VAL_CTO DECIMAL(17,2),
    VAL_BAS DECIMAL(17,2),
    OBS_LIQ VARCHAR2(200),
    FEC_REG DATE,
    USUARIO VARCHAR(20),
    
   
    SUB_TOT NUMBER(17,2),
    INTERES NUMBER(17,2),
    SANCION NUMBER(17,2),
    DECUENT NUMBER(17,2),
    TOTAL NUMBER(17,2),
    ESTADO VARCHAR(2)
    
); 

COMMENT ON TABLE SL_LIQESTAMPILLAS IS 'SL_ LIQUIDACIONES DE ESTAMPILLAS';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.ID IS 'ID UNICO';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.AGE_REC IS 'AGENTE RECAUDADOR';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.VIG_LIQ IS 'VIGENCIA';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.NRO_LIQ IS 'NRO DE LIQUIDACION';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.PER_LIQ IS 'PERIODO DE LIQUIDACION';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.FEC_LIQ IS 'FECHA DE LIQUIDACION';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.NUM_CTO IS 'NUMERO DE CONTRATO';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.FEC_SUS IS 'FECHA DE SUSCRIPCION';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.FEC_VEN IS 'FECHA DE VENCIMIENTO';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.ADI_CTO IS 'ADICION CONTRATO';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.OBJ_CTO IS 'OBJETO DEL CONTRATO';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.VAL_CTO IS 'VALOR DEL CONTRATO';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.VAL_BAS IS 'VALOR BASE (SIN IVA PARA REG COMUN)';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.OBS_LIQ IS 'OBSERVACION DE LA LIQUIDACION';
COMMENT ON COLUMN SL_LIQESTAMPILLAS.FEC_REG IS 'FECHA DE REGISTRO';
COMMENT ON COLUMN SL_LIQESTAMPILLAS.USUARIO IS 'USUARIO';

COMMENT ON COLUMN SL_LIQESTAMPILLAS.SUB_TOT IS 'SUB TOTAL';
COMMENT ON COLUMN SL_LIQESTAMPILLAS.INTERES IS 'INTERESES';
COMMENT ON COLUMN SL_LIQESTAMPILLAS.SANCION IS 'SANCIONES';
COMMENT ON COLUMN SL_LIQESTAMPILLAS.DECUENT IS 'DESCUENTO';
COMMENT ON COLUMN SL_LIQESTAMPILLAS.TOTAL IS 'TOTAL';
COMMENT ON COLUMN SL_LIQESTAMPILLAS.ESTADO IS 'ESTADO';

    


ALTER TABLE SL_LIQESTAMPILLAS
 ADD CONSTRAINT SL_LIQESTAMPILLAS_PK
 PRIMARY KEY
 (ID);

ALTER TABLE SL_LIQESTAMPILLAS
 ADD UNIQUE (VIG_LIQ, NRO_LIQ);

ALTER TABLE SL_LIQESTAMPILLAS
 ADD FOREIGN KEY (AGE_REC) 
 REFERENCES TERCEROS (TER_NIT);


CREATE TABLE SL_DETLIQ (
    ID      NUMBER(20),
    ID_LIQ  NUMBER(20),
    COD_IMP VARCHAR2(4),
    TAR_IMP NUMBER(10,4),
    VAL_BAS NUMBER(10,4),
    FEC_REG DATE,
    USUARIO VARCHAR(20)
); 


COMMENT ON TABLE SL_DETLIQ IS 'SL DETALLE DE LIQUIDACION'
/

COMMENT ON COLUMN SL_DETLIQ.ID IS 'ID CONSECUTIVO'
/

COMMENT ON COLUMN SL_DETLIQ.ID_LIQ IS 'ID DE LIQUIDACION'
/

COMMENT ON COLUMN SL_DETLIQ.COD_IMP IS 'CODIGO DE IMPUESTO'
/

COMMENT ON COLUMN SL_DETLIQ.TAR_IMP IS 'TARIFA DE IMPUESTO'
/

COMMENT ON COLUMN SL_DETLIQ.VAL_BAS IS 'VALOR BASE'
/

COMMENT ON COLUMN SL_DETLIQ.FEC_REG IS 'FECHA DE REGISTRO'
/

COMMENT ON COLUMN SL_DETLIQ.USUARIO IS 'USUARIO'
/
ALTER TABLE SL_DETLIQ
 ADD CONSTRAINT SL_DETLIQ_PK
 PRIMARY KEY
 (ID)
/

ALTER TABLE SL_DETLIQ
 ADD CONSTRAINT SL_DETLIQ_FK_IMP 
 FOREIGN KEY (COD_IMP) 
 REFERENCES IMPUESTOS (IMP_COD)
/

CREATE TABLE SL_PAGOS (
    ID NUMBER(20),
    ID_LIQ NUMBER(20),
    FEC_PAGO DATE,
    VAL_PAGO DECIMAL(17,2),
    FEC_REG DATE,
    USUARIO VARCHAR(20),
    ESTADO VARCHAR(2)
); 


COMMENT ON TABLE SL_PAGOS IS 'SL PAGOS A DECLARACIONES DE ESTAMPILLAS'
/

COMMENT ON COLUMN SL_PAGOS.ID IS 'ID'
/

COMMENT ON COLUMN SL_PAGOS.ID_LIQ IS 'ID LIQUIDACION'
/

COMMENT ON COLUMN SL_PAGOS.FEC_PAGO IS 'FECHA DE PAGO DE LA LIQUIDACION'
/

COMMENT ON COLUMN SL_PAGOS.VAL_PAGO IS 'VALOR DEL PAGO'
/

COMMENT ON COLUMN SL_PAGOS.FEC_REG IS 'FECHA DE REGISTRO'
/

COMMENT ON COLUMN SL_PAGOS.USUARIO IS 'USUARIO'
/
COMMENT ON COLUMN SL_PAGOS.ESTADO IS 'ESTADO'
/
ALTER TABLE SL_PAGOS
 ADD CONSTRAINT SL_PAGOS_PK
 PRIMARY KEY
 (ID)
/

ALTER TABLE SL_PAGOS
 ADD CONSTRAINT SL_PAGOS_LIQ_FK 
 FOREIGN KEY (ID_LIQ) 
 REFERENCES SL_LIQESTAMPILLAS (ID)
/

ALTER TABLE SL_AGETDPTA
 ADD CONSTRAINT SL_AGETDPTA_FK_TER 
 FOREIGN KEY (TER_NIT) 
 REFERENCES TERCEROS (TER_NIT)
 /