CREATE TABLE DIRECCIONES_EXTERNAS
(
  ID      NUMBER,
  NOMBRE  VARCHAR2(50),
  URL     VARCHAR2(200)
);


ALTER TABLE DIRECCIONES_EXTERNAS ADD (
  PRIMARY KEY
 (ID));
 
 ALTER TABLE DERWEB.DIRECCIONES_EXTERNAS
 ADD (ACTUALIZACION  DATE);
 
INSERT INTO DIRECCIONES_EXTERNAS
   (ID, NOMBRE, URL, ACTUALIZACION)
 VALUES
   (1, 'Aplicación Auditor', 'https://drive.google.com/file/d/0B8AJ_Vr2tT1FQnFTZ3lMLUE2Mjg/view?usp=sharing', TO_DATE('05/28/2015 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
 