ALTER TABLE SL_LIQESTAMPILLAS
MODIFY(VAL_CTO NUMBER(20,5));


ALTER TABLE SL_LIQESTAMPILLAS
MODIFY(VAL_BAS NUMBER(20,5));


ALTER TABLE SL_LIQESTAMPILLAS
MODIFY(SUB_TOT NUMBER(20,5));


ALTER TABLE SL_LIQESTAMPILLAS
MODIFY(INTERES NUMBER(20,5));


ALTER TABLE SL_LIQESTAMPILLAS
MODIFY(SANCION NUMBER(20,5));


ALTER TABLE SL_LIQESTAMPILLAS
MODIFY(DECUENT NUMBER(20,5));


ALTER TABLE SL_LIQESTAMPILLAS
MODIFY(TOTAL NUMBER(20,5));

ALTER TABLE SL_DETLIQ
MODIFY(TAR_IMP NUMBER(20,5));


ALTER TABLE SL_DETLIQ
MODIFY(VAL_BAS NUMBER(20,5));