ALTER TABLE SL_LIQESTAMPILLAS
 ADD (REPLICADO  VARCHAR2(2));

ALTER TABLE SL_LIQESTAMPILLAS
 ADD (VIG_PAG  VARCHAR2(4));

ALTER TABLE SL_LIQESTAMPILLAS
 ADD (PER_PAG  VARCHAR2(2));
 
UPDATE SL_LIQESTAMPILLAS SET REPLICADO = 'NO';
COMMIT;